fix: some changes
dscnitrourkela/project-dates pull request #160
Opened 2024-07-08 15:10 UTC by Srish-ty

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [x] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2024-07-08 15:46 UTC, Srish-ty commented
@Shurtu-gal , please review

2024-07-08 17:42 UTC, Srish-ty commented
@Shurtu-gal please review

2024-07-08 18:27 UTC, dsc-nitr requested changes

2024-07-08 18:27 UTC, dsc-nitr commented on api/src/apollo/Event/mutations.ts
> +  /* authorize: (_parent, args, ctx) =>
Add permissions here as well.

2024-07-08 18:27 UTC, dsc-nitr commented on api/src/helpers/auth/checkPermissions.ts
> +    console.log(permissions);
nit: remove logs

2024-07-08 20:24 UTC, Srish-ty commented on api/src/apollo/Event/mutations.ts
> +  /* authorize: (_parent, args, ctx) =>
done. https://github.com/dscnitrourkela/project-dates/pull/160/commits/10aeecccc753efa066166e6a29cefb82de7d0ae2

2024-07-08 20:24 UTC, Srish-ty commented on api/src/helpers/auth/checkPermissions.ts
> +    console.log(permissions);
removed. https://github.com/dscnitrourkela/project-dates/pull/160/commits/10aeecccc753efa066166e6a29cefb82de7d0ae2

2024-07-09 03:26 UTC, dsc-nitr approved these changes

2024-07-09 03:26 UTC, merged